### ISSUE TITLE
Generate package for MacOS >= 10

### ISSUE THREAD

**Issue by jjazzboss** [apache/netbeans-nbpackage#41]
I successfully created a .pkg file using nbpackage on Mac OS 14. Some of my Mac users complain that the package can not be run on old MacOS < 11.

I found that Package.swift.template introduces a limitation:
```
  platforms: [
        .macOS(.v11)
    ],
```
Do you know if can safely change this to macOS(.v10_16) ?    (sorry if it's a trivial question but I don't own a MacOS and can't do tests)

**Comment by neilcsmith-net** [comment]
This was updated in supporting Apple Silicon. If you're only building for x86_64 then you should be fine changing this back.

At the moment this file template can't be overridden by options. I'll leave this issue open for now while looking at that. In the meantime you could use `image-only`, update the relevant file, and then `input-image`.

**Comment by jjazzboss** [comment]
ok thanks

**Comment by neilcsmith-net** [comment]
I'm going to close this as I'm not sure there's a need to expose this template.  However, besides editing the image manually with the `image-only` approach, I realised you can also use the `package.merge` and `package.remove` options to do this.

Next to your configuration properties file add a `merge` folder, copy the `Package.swift` file to `merge/macos-launcher-src/Package.swift` and edit it as you see fit.

Inside your configuration file, alter those two properties to be

```
package.merge=${CONFIG}/merge
package.remove={macos-launcher-src/Package.swift}
```

Merge will not overwrite anything, hence the need to remove that file as well.
